export enum PracticeSpecialty {
  GeneralPractice = "GeneralPractice",
  Physiotherapy = "Physiotherapy",
  Dentistry = "Dentistry",
  Radiology = "Radiology",
  Podiatry = "Podiatry",
  Optometry = "Optometry",
  Chiropractor = "Chiropractor",
  Osteopathic = "Osteopathic",
  Dietitian = "Dietitian",
  Nutritionist = "Nutritionist",
  Surgeon = "Surgeon",
  Cardiology = "Cardiology",
  Neurology = "Neurology",
  Orthopedics = "Orthopedics",
  Pediatrics = "Pediatrics",
  Psychology = "Psychology",
  Psychiatry = "Psychiatry",
  Urology = "Urology"
}
