stages:
  - test

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.test_template: &test_definition
  stage: test
  image: node:20-alpine

  before_script:
    - npm install --cache .npm --prefer-offline
    - npm install -g @angular/cli@21.0.4 
    - mkdir -p src/environments
    - echo "$ENV_DEVELOPMENT" > src/environments/environment.development.ts
    - echo "$ENV_DEVELOPMENT" > src/environments/environment.ts

  script:
    # --- Project 1 ---
    - echo "Testing Project 1 with Vitest..."
    - ng test HealthcareClient

    # --- Project 2 ---
    - echo "Testing Project 2 with Vitest..."
    - ng test practice

  artifacts:
    name: "test-results-$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - coverage/
      - junit/
    reports:
      junit: junit/*.xml

test:mr:
  <<: *test_definition
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:master:
  <<: *test_definition
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
