stages:
  - lint
  - test
  - build
variables:
  NODE_ENV: ci
  NODE_IMAGE: 'node:20-bullseye'
  COVERAGE_MINIMUM: '85'
lint-format:
  stage: lint
  image: $NODE_IMAGE
  script:
    - npm ci
    - 'npx prettier --check "**/*.{ts,html,css,scss,md,json,scss.d.ts}"'
    - npx eslint src/**/*.ts --max-warnings=0
  rules:
    - if: >-
        $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE ==
        "merge_request_event"
      when: always
#test-with-coverage:
#  stage: test
#  image: $NODE_IMAGE
#  script:
#    - npm ci
#    - >-
#      npx jest --ci --coverage --detectOpenHandles --reduced-fixtures
#      --maxWorkers=2
#    - |
#      COVERAGE=$(node - <<'EOF'
#      const fs = require('fs');
#      const file = fs.readFileSync('coverage/coverage-summary.json', 'utf8');
#      const json = JSON.parse(file);
#      const pct = json.total.lines.pct;
#      console.log(pct);
#      EOF
#      )
#      echo "Overall line coverage = $COVERAGE %"
#      if (( $(echo "$COVERAGE < $COVERAGE_MINIMUM" | bc -l) )); then
#        echo "❌ Coverage $COVERAGE% is below the required $COVERAGE_MINIMUM%";
#        exit 1;
#      fi
#  rules:
#    - if: >-
#        $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE ==
#        "merge_request_event"
#      when: always
build-prod:
  stage: build
  image: $NODE_IMAGE
  script:
    - npm ci
    - npx ng build --configuration production
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success

