stages:
  - test

.test_template: &test_definition
  stage: test

  image: docker:27-cli

  services:
    - name: docker:27-dind
      alias: docker

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker info

    # Create Angular environment files before building the test image
    - mkdir -p environment
    - echo "$ENV_DEVELOPMENT" > environment/environment.development.ts
    - echo "$ENV_DEVELOPMENT" > environment/environment.ts

    - mkdir -p src/environments
    - echo "$ENV_DEVELOPMENT" > src/environments/environment.development.ts
    - echo "$ENV_DEVELOPMENT" > src/environments/environment.ts

  script:
    - echo "Building Angular test image..."
    - docker build --network=host -f Dockerfile.angular -t angular-tests .
    - mkdir -p coverage junit
    - docker run --rm -v "$CI_PROJECT_DIR/coverage:/app/coverage" -v "$CI_PROJECT_DIR/junit:/app/junit" angular-tests

  artifacts:
    name: "test-results-$CI_COMMIT_REF_SLUG"
    when: always
    paths:
      - coverage/
      - junit/
    reports:
      junit: junit/*.xml

test:mr:
  <<: *test_definition
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test:master:
  <<: *test_definition
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
