FROM node:22-bookworm

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci --prefer-offline --include=dev

COPY . .

CMD ["sh", "-c", "npm run test:p1 && npm run test:p2"]
